### ISSUE TITLE
Could not pass event AsyncPlayerChatEvent to Guilds

### ISSUE THREAD

**Issue by mibby** [darbyjack/Guilds-Plugin#68] opened 2017-10-06 22:18 UTC
Guilds dev 176

```
[13:52:08] [Async Chat Thread - #1/ERROR]: Could not pass event AsyncPlayerChatEvent to Guilds v1.9.0-BETA
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1230]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.12.2.jar:git-Paper-1230]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1230]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) [patched_1.12.2.jar:git-Paper-1230]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:496) [patched_1.12.2.jar:git-Paper-1230]
	at net.minecraft.server.v1_12_R1.PlayerConnection.chat(PlayerConnection.java:1374) [patched_1.12.2.jar:git-Paper-1230]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1289) [patched_1.12.2.jar:git-Paper-1230]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [patched_1.12.2.jar:git-Paper-1230]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.NullPointerException
	at me.glaremasters.guilds.listeners.ChatListener.onPlayerChat(ChatListener.java:35) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor605.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1230]
	... 12 more
```

**Comment by prozhong** [comment] 2017-11-22 12:28
caused by https://github.com/darbyjack/Guilds-Plugin/blob/master/src/main/java/me/glaremasters/guilds/database/databases/mysql/MySql.java#L156

                    while (resultSet.next()) {
                        Guild guild = new Guild(name);
                        guild.setPrefix(data.get(name));

                        UUID uuid = UUID.fromString(resultSet.getString("uuid"));
                        GuildRole role = GuildRole.getRole(resultSet.getInt("role"));

                        guild.addMember(uuid, role);

                        guilds.put(name, guild);
                    }
every member get his own guild, so can't find his guildmaster

**Comment by prozhong** [comment] 2017-11-22 12:31
If the guildmaster is offline it throws me NPE
https://pastebin.com/5EXR5utR

shall we use Bukkit.getOfflinePlayer?
https://github.com/darbyjack/Guilds-Plugin/blob/master/src/main/java/me/glaremasters/guilds/placeholders/Placeholders.java#L28

**Comment by darbyjack** [comment] 2017-11-22 15:58
Should be all fixed now

**Closed by darbyjack** 2017-11-22 15:58 UTC
